# Generated by Django 3.0.3 on 2020-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200917_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlight',
            field=models.TextField(),
        ),
    ]
